### PR TITLE
bugfix: we closed listener's fd which was closed.

### LINKED ISSUE #1806: 9: Bad file descriptor
I'm using Openresty 1.17.8.2 to stream data from Redis to clients. So there are long open connections to Redis using [lua-resty-redis](https://github.com/openresty/lua-resty-redis) and long open connections to the clients. Lately I'm seeing these error messages:

`2020/10/21 08:46:31 [emerg] 27167#3261: lua pipe child close() socket xx.xx.x.xx:443 failed (9: Bad file descriptor)`

The unexpected thing: I increased the log level from `warn` to `debug` and the error messages disappear. Any idea how I can further debug the error?

This is how it actually looks in the logs (`docker logs -f e0dfb6f130 | grep descriptor | uniq -c`), the number at the beginning of the line being the number of occurrences of the very same line:
```
     30 2020/10/21 11:48:19 [emerg] 822#30882: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:19 [emerg] 822#30882: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:19 [emerg] 822#30882: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

      1 2020/10/21 11:48:22 [emerg] 816#30887: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:48:22 [emerg] 816#30887: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:48:22 [emerg] 816#30887: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:22 [emerg] 816#30887: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:22 [emerg] 816#30887: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:22 [emerg] 816#30887: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

      1 2020/10/21 11:48:51 [emerg] 841#30972: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:48:51 [emerg] 841#30972: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:48:51 [emerg] 841#30972: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:51 [emerg] 841#30972: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:51 [emerg] 841#30972: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:48:51 [emerg] 841#30972: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

      1 2020/10/21 11:49:21 [emerg] 826#31034: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:49:21 [emerg] 826#31034: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:49:21 [emerg] 826#31034: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
     30 2020/10/21 11:49:21 [emerg] 826#31034: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:49:21 [emerg] 826#31034: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:49:21 [emerg] 826#31034: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

      1 2020/10/21 11:49:48 [emerg] 822#31161: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:49:48 [emerg] 822#31161: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:49:48 [emerg] 822#31161: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
     30 2020/10/21 11:49:48 [emerg] 822#31161: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:49:48 [emerg] 822#31161: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:49:48 [emerg] 822#31161: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

     31 2020/10/21 11:50:00 [emerg] 812#31162: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     31 2020/10/21 11:50:00 [emerg] 812#31162: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     31 2020/10/21 11:50:00 [emerg] 812#31162: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

     31 2020/10/21 11:50:09 [emerg] 812#31207: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     31 2020/10/21 11:50:09 [emerg] 812#31207: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     31 2020/10/21 11:50:09 [emerg] 812#31207: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

     31 2020/10/21 11:50:10 [emerg] 812#31215: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     31 2020/10/21 11:50:10 [emerg] 812#31215: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     31 2020/10/21 11:50:10 [emerg] 812#31215: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

      1 2020/10/21 11:50:25 [emerg] 821#31279: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:50:25 [emerg] 821#31279: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:50:25 [emerg] 821#31279: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
     30 2020/10/21 11:50:25 [emerg] 821#31279: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:50:25 [emerg] 821#31279: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:50:25 [emerg] 821#31279: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)

      1 2020/10/21 11:51:44 [emerg] 816#31537: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:51:44 [emerg] 816#31537: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
      1 2020/10/21 11:51:44 [emerg] 816#31537: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
     30 2020/10/21 11:51:44 [emerg] 816#31537: lua pipe child close() socket xx.xx.x.xx:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:51:44 [emerg] 816#31537: lua pipe child close() socket 172.17.110.1:8080 failed (9: Bad file descriptor)
     30 2020/10/21 11:51:44 [emerg] 816#31537: lua pipe child close() socket xx.xx.x.xx:8443 failed (9: Bad file descriptor)
 ```

### LINKED ISSUE #1830: Mutiple worker_processes cause `Bad file descriptor` on Alpine3.12 openresty/1.19.3.1
Everything works fine under  **ONE**  nginx worker.
More than **ONE**  nginx workers and access "redis/file/shell" will cause this issue.

Also found on alpine3.11 openresty/1.17.8.2
Environment as below:
/ # nginx -V
nginx version: openresty/1.19.3.1
built by gcc 9.3.0 (Alpine 9.3.0) 
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always -g3' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

```log
local/openresty/luajit/lib/lua/5.1/?.so, context: init_worker_by_lua*
2020/11/27 09:20:35 [emerg] 245#246: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)
2020/11/27 09:20:35 [emerg] 245#246: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)
2020/11/27 09:20:35 [emerg] 245#246: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)
2020/11/27 09:20:35 [emerg] 242#247: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)
2020/11/27 09:20:35 [emerg] 242#247: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)
2020/11/27 09:20:35 [emerg] 242#247: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)
```

### PR DESCRIPTION
**Pull request by spacewander**
fix #1806
fix #1830

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by spacewander** [comment]
Test case is in https://github.com/openresty/lua-resty-core/pull/331

File: src/ngx_http_lua_pipe.c [hunk 1]
```diff
@@ -688,7 +688,7 @@ ngx_http_lua_ffi_pipe_spawn(ngx_http_lua_ffi_pipe_proc_t *proc,
         /* close listening socket fd */
         ls = ngx_cycle->listening.elts;
         for (i = 0; i < ngx_cycle->listening.nelts; i++) {
-            if (ngx_close_socket(ls[i].fd) == -1) {
+            if (ls[i].fd != -1 && ngx_close_socket(ls[i].fd) == -1) {
```
Comment (thibaultcha) [inline src/ngx_http_lua_pipe.c:691]:
```suggestion
            if (ls[i].fd != (ngx_socket_t) -1 && ngx_close_socket(ls[i].fd) == -1) {
```

Maybe slightly clearer even if we should be fine here in UNIX.

**Review by thibaultcha — APPROVED** [review]

File: src/ngx_http_lua_pipe.c [hunk 2]
```diff
@@ -688,7 +688,7 @@ ngx_http_lua_ffi_pipe_spawn(ngx_http_lua_ffi_pipe_proc_t *proc,
...
                 ngx_log_error(NGX_LOG_EMERG, ngx_cycle->log, ngx_socket_errno,
```
Comment (thibaultcha) [inline src/ngx_http_lua_pipe.c:692]: As a side note, maybe these logs shouldn't have such a high severity. A warning maybe, but an error here should not impact the rest of the code path, so anything above that seems harder to justify, especially so `emerg`.

File: src/ngx_http_lua_pipe.c [hunk 3]
```diff
@@ -688,8 +688,10 @@ ngx_http_lua_ffi_pipe_spawn(ngx_http_lua_ffi_pipe_proc_t *proc,
         /* close listening socket fd */
         ls = ngx_cycle->listening.elts;
         for (i = 0; i < ngx_cycle->listening.nelts; i++) {
-            if (ngx_close_socket(ls[i].fd) == -1) {
-                ngx_log_error(NGX_LOG_EMERG, ngx_cycle->log, ngx_socket_errno,
+            if (ls[i].fd != (ngx_socket_t) -1 &&
+                ngx_close_socket(ls[i].fd) == -1)
+            {
+                ngx_log_error(NGX_LOG_WARN, ngx_cycle->log, ngx_socket_errno,
```
Comment (thibaultcha) [inline src/ngx_http_lua_pipe.c:694]: I'm glad that we seem to agree on the severity level; if we are to downgrade this log to warn (which I believe is appropriate), don't we ought it too to lower the below logs as well? That is, all calls to `ngx_log_error` that aren't followed by `exit()` I mean.

That said, not a blocker for this fix of course, since the above check in the condition is all this PR should need :+1:

**Review by thibaultcha — APPROVED** [review]
